version: '3.7'

services:
  shiro-chan-server:
    build: .
    restart: always
    container_name: EasternTalesShelf-website  # Custom container name
    environment:
      - FLASK_ENV=development  # Set to development or production based on your need
      - DOPPLER_TOKEN=${DOPPLER_TOKEN_EASTERN_SHELF}  # Use Doppler service token for secret injection
    networks:
      - external-containers
      - phpmyadmin_gpt_db
    volumes:
      - .:/app  # Maps the app directory on your host to /app in your container
      - logs_volume:/app/logs

networks:
  external-containers:
    external: true
  phpmyadmin_gpt_db:
    external: true

volumes:
  logs_volume:
