services:
  shiro-chan-server:
    build: .
    restart: always
    container_name: EasternTalesShelf-website  # Custom container name
    environment:
      - FLASK_ENV  # Set to development or production based on your need
      - DOPPLER_TOKEN=${DOPPLER_TOKEN_EASTERN_SHELF}  # Use Doppler service token for secret injection
    command: >
      doppler run -- gunicorn
      --worker-class gevent
      --workers 1
      --bind 0.0.0.0:80
      --timeout 120
      --keep-alive 5
      --log-level debug
      app.app:app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Limit log files to 20MB
        max-file: "3"    # Keep only 3 rotated log files
    networks:
      - external-containers
      - phpmyadmin_gpt_db
    volumes:
      - .:/app  # Maps the app directory on your host to /app in your container
      - logs_volume:/app/logs

networks:
  external-containers:
    external: true
  phpmyadmin_gpt_db:
    external: true

volumes:
  logs_volume:
