version: '3.8'

services:
  shiro-chan-server:
    build: .
    restart: always
    container_name: EasternTalesShelf-website  # Custom container name
    environment:
      - FLASK_ENV=production
      - VAULT_ADDR
      - VAULT_ROLE_ID_shiro_chan_project
      - VAULT_SECRET_ID_shiro_chan_project
    networks:
      - external-containers
      - phpmyadmin_gpt_db
    volumes:
      - ./app:/app  # Maps the app directory on your host to /app in your container
      - logs_volume:/app/logs

networks:
  external-containers:
    external: true
  phpmyadmin_gpt_db:
    external: true

volumes:
  logs_volume:
