version: '3.7'
services:
  shiro-chan-server:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: easterntalesshelf-fastapi-updater  # Custom container name
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN_EASTERN_SHELF}  # Doppler token for secret injection
      - FLASK_ENV  
    networks:
      - phpmyadmin_gpt_db
    volumes:
      - ./app:/app  # Maps the app directory on your host to /app in your container
      - /home/ubuntu/docker/logs:/app/logs

networks:
  phpmyadmin_gpt_db:
    external: true
volumes:
  logs_volume:
