name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # Run on push to any branch # Ignore branches created by Dependabot
    paths:
      - 'requirements.txt'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/shiroepl/easterntalesshelf:latest
            ghcr.io/shiroepl/easterntalesshelf:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: type=registry,ref=ghcr.io/shiroepl/easterntalesshelf:latest
          cache-to: type=inline