name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  
    paths:
      - 'requirements.txt'
      - 'Dockerfile'
      - 'app/**'  # Dodaj to żeby rebuildować gdy zmienia się kod!

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Lowercase repository name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        
      - name: Build and push with buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64  # Explicit dla twojego ARM VPS
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}:latest
            ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          
      - name: Tag for local use
        run: |
          # Pull i retag dla local Docker daemon
          docker pull ghcr.io/${{ env.REPO_LC }}:latest
          docker tag ghcr.io/${{ env.REPO_LC }}:latest easterntalesshelf:local
          
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
