name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  
    paths:
      - 'requirements.txt'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Lowercase repository name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        
      - name: Build and Tag for Both Local and GitHub Registry
        run: |
          echo "Checking out the branch that triggered the workflow..."
          git checkout ${{ github.ref_name }}  # Switch to the correct branch

          echo "Building image for both local use and GitHub Container Registry..."
          # Build the image with local tag
          docker build -t easterntalesshelf:local .
          
          # Tag the same image for GitHub Container Registry 
          docker tag easterntalesshelf:local ghcr.io/${{ env.REPO_LC }}:latest
          docker tag easterntalesshelf:local ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}
          
          # Push to GitHub Container Registry
          docker push ghcr.io/${{ env.REPO_LC }}:latest
          docker push ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}