name: Deploy Application

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/dependabot/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'docker-compose.yml'

  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Git Pull Changes
        working-directory: /home/ubuntu/docker/EasternTalesShelf  
        run: |
          git pull
          git checkout ${{ github.ref_name }}

      - name: Restart Containers
        working-directory: /home/ubuntu/docker/EasternTalesShelf  
        run: |
          echo "Restarting containers for branch: ${{ github.ref_name }}"
          docker compose down && docker compose up -d

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🚀 Deployment Status"
          description: |
            GitHub Actions has **${{ job.status }}** the deployment.
            Branch: `${{ github.ref_name }}`
            Commit: `${{ github.sha }}`
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
          url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          username: "GitHub Actions"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
