name: Deploy to VPS via Tailscale

on:
  push:
    branches:
      - main  # Runs on push to main
      - updater-for-mangaupdates # testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Setup SSH key with ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS via SSH
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.VPS_HOST }} "cd some_programs && mkdir this_was_made_via_github_cl"

      # ✅ Send Discord Notification on Success or Failure
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()  # Ensures it runs no matter what (success/failure)
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🚀 VPS Deployment Status"
          description: "GitHub Actions has **${{ job.status }}** the deployment.\nBranch: `${{ github.ref }}`\nCommit: `${{ github.sha }}`"
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}  # Green if success, red if failed
          url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          username: "GitHub Actions"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
