name: Deploy on Self-Hosted VPS

on:
  push:
    branches:
      - '**'  # Run on push to any branch
    paths-ignore:
      - '**/dependabot/**'  # Ignore branches created by Dependabot

jobs:
  deploy:
    runs-on: self-hosted  # Use your VPS runner
    steps:

      - name: Execute deployment commands
        working-directory: /home/ubuntu/docker/EasternTalesShelf  
        run: |
          echo "Deploying branch: ${{ github.ref_name }}"
          git checkout ${{ github.ref_name }}  # Dynamically pull the correct branch
          # Check if Dockerfile or docker-compose.yml changed, then build
          if git diff --name-only HEAD~1 | grep -qE 'Dockerfile'; then
            echo "Dockerfile or Compose changed. Rebuilding Docker image..."
            docker compose build
          else
            echo "No Dockerfile changes detected. Skipping build."
          fi

          # ReStart or update the container
          docker compose down && docker compose up -d

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🚀 VPS Deployment Status"
          description: "GitHub Actions has **${{ job.status }}** the deployment.\nBranch: `${{ github.ref }}`\nCommit: `${{ github.sha }}`"
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
          url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          username: "GitHub Actions"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
