name: Deploy on Self-Hosted VPS

on:
  push:
    branches:
      - main
      - updater-for-mangaupdates

jobs:
  deploy:
    runs-on: self-hosted  # This specifies to use your self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute deployment commands
        working-directory: /home/ubuntu  # ✅ This applies to this entire step
        run: |
          ls  # This now runs in /home/ubuntu
          cd some_programs
          mkdir this_folder_is_from_self_hosted_runner
          # Add any other deployment commands here

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🚀 VPS Deployment Status"
          description: "GitHub Actions has **${{ job.status }}** the deployment.\nBranch: `${{ github.ref }}`\nCommit: `${{ github.sha }}`"
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
          url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          username: "GitHub Actions"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
